spring.application.name=Gateway
server.port=8080

spring.cloud.gateway.routes[0].id=cliente-service
spring.cloud.gateway.routes[0].uri=http://cliente-service:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/client/**

spring.cloud.gateway.routes[1].id=conta-service
spring.cloud.gateway.routes[1].uri=http://conta-service:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/conta/**

spring.cloud.gateway.routes[2].id=transacao-service
spring.cloud.gateway.routes[2].uri=http://transacao-service:8083
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/transacao/**

spring.cloud.gateway.routes[3].id=pagamento-service
spring.cloud.gateway.routes[3].uri=http://pagamento-service:8084
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/pagamento/**